version: 2
jobs:
  build:
    docker:
      - image: dott/circleci:pyang
        auth:
          username: dott
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: "npm install -g n"
      - run: "n 12"
      - run: "node -v"